# HASTAG = COMENTÁRIO EM UMA LINHA (SÓ EM PYTHON)
""" ASPAS TRIPLAS = COMENTÁRIO EM VÁRIAS LINHAS
PEMDAS: ORDEM DOS OPERADORES NA MATEMÁTICA
PARENTESES
EXPONENTE (ELEVADO)
MULTIPLICAÇÃO = DIVISÃO (DIREITA PRA ESQUERDA)
ADIÇÃO = SUBTRAÇÃO (DIREITA PRA ESQUERDA)
"""

print(5+5)  # 10
print(5-5)  # 0
print(5*5)  # 25
print(5/5)  # 1
print(5 ** 5)  # ELEVADO: 3125
print(5 // 2)  # DIVISÃO INTEIRA: 2
print(15 % 4)  # MÓDULO (RESTO): 3